export const myFileds = [
    {
        _id: "field-id-1",
        name: 'Demo Field 1',
        location: 'Sample Location 1',
        postalCode: '12345',
        gate: 'Gate A',
        link: 'https://example.com/field1',
        fee: 50,
        shower: true,
        showerRating: 4,
        toilet: true,
        toiletRating: 3,
        rating: 4,
        facilitiesRating: 4,
        review: 'Nice field with good facilities',
        childrenPlayground: false,
        childrenPlaygroundRating: null,
        foodCourtNearby: true,
        foodCourtNearbyRating: 5,
        whereToEatAndDrink: 'Nearby restaurant and bar',
        whereToEatAndDrinkRating: 4,
        deposit: 100,
        paymentStatus: 'Paid',
        areas: ['Field A', 'Field B'],
        instructionOrNote: 'Park at the main parking area.'
    },
    {
        _id: "field-id-2",
        name: 'Demo Field 2',
        location: 'Sample Location 2',
        postalCode: '54321',
        gate: 'Gate B',
        link: 'https://example.com/field2',
        fee: 70,
        shower: true,
        showerRating: 5,
        toilet: true,
        toiletRating: 4,
        rating: 4.5,
        facilitiesRating: 4.2,
        review: 'Well-maintained field with excellent facilities',
        childrenPlayground: true,
        childrenPlaygroundRating: 4,
        foodCourtNearby: true,
        foodCourtNearbyRating: 4,
        whereToEatAndDrink: 'Cafeteria within walking distance',
        whereToEatAndDrinkRating: 4,
        deposit: 120,
        paymentStatus: 'Unpaid',
        areas: ['Field C', 'Field D'],
        instructionOrNote: 'Access through Gate B.'
    }
];